import { Inter } from "next/font/google";
import "../globals.css";
import Menu from "@/component/MenuLateral";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ERP - Para o seu negocio crescer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
      <Menu />

        {children}
      </body>
    </html>
  );
}
